// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzVpy7ZgbnI6emH5f48JHhbj2hVRH_PFg',
    appId: '1:331394964996:web:9e120780791c199cbe5f51',
    messagingSenderId: '331394964996',
    projectId: 'quip-664c9',
    authDomain: 'quip-664c9.firebaseapp.com',
    databaseURL: 'https://quip-664c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quip-664c9.firebasestorage.app',
    measurementId: 'G-B4M647WXVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU31kfBjtTNqfsahaBMBtlRamMltN7GMc',
    appId: '1:331394964996:android:aa1d4d0216adccedbe5f51',
    messagingSenderId: '331394964996',
    projectId: 'quip-664c9',
    databaseURL: 'https://quip-664c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quip-664c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKLfozjFoSxEp-YWO8afZc_vJtKTIpXrU',
    appId: '1:331394964996:ios:8c6258e7508d2323be5f51',
    messagingSenderId: '331394964996',
    projectId: 'quip-664c9',
    databaseURL: 'https://quip-664c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quip-664c9.firebasestorage.app',
    iosBundleId: 'com.example.quip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzVpy7ZgbnI6emH5f48JHhbj2hVRH_PFg',
    appId: '1:331394964996:web:4492900dfc8d9433be5f51',
    messagingSenderId: '331394964996',
    projectId: 'quip-664c9',
    authDomain: 'quip-664c9.firebaseapp.com',
    databaseURL: 'https://quip-664c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quip-664c9.firebasestorage.app',
    measurementId: 'G-2WXYP7WRD1',
  );

}